#include "type.h"
#include "stdio.h"
#include "const.h"
#include "protect.h"
#include "string.h"
#include "fs.h"
#include "proc.h"
#include "tty.h"
#include "console.h"
#include "global.h"
#include "keyboard.h"
#include "keymap.h"
#include "proto.h"

PRIVATE struct kb_inbuf kb_in;
PRIVATE int code_with_E0;
PRIVATE int shift_l;	/* left shift state */
PRIVATE int shift_r;	/* right shift state */
PRIVATE int alt_l;		/* left alt state */
PRIVATE int alt_r;		/* right alt state */
PRIVATE int ctrl_l;		/* left ctrl state */
PRIVATE int ctrl_r;		/* right ctrl state */
PRIVATE int caps_lock;	/* Caps Lcok */
PRIVATE int num_lock;	/* Num Lock */
PRIVATE int scroll_lock;	/* Scroll Lock */
PRIVATE int column;

PRIVATE u8 get_byte_from_kb_buf();
PRIVATE void set_leds();
PRIVATE void kb_wait();
PRIVAET void kb_ack();

/**
 * keyboard_handler
 * 
 * <Ring 0> Handles the interrupts generated by the keyboard controller.
 * 
 * @param irq: The IRQ corresponding to the keyboard, unused here.
 *
 */
PUBLIC void keyboard_handler(int irq)
{
	u8 scan_code = in_byte(KB_DATA);

	if(kb_in.count < KB_IN_BYTES) {
		*(kb_in.p_head) = scan_code;
		kb_in.p_head++;
		if(kb_in.p_head == kb_in.buf + KB_IN_BYTES)
			kb_in.p_head = kb_in.buf;
		kb_in.count++;
	}
}
